import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['lcov', 'text'],
      reportsDirectory: './coverage',
      include: ['src/**/*.ts'],
      // Mirrored in sonar.coverage.exclusions — a file skipped here emits no
      // lcov entry, so Sonar must not count it as uncovered either.
      exclude: [
        // Machine-generated by server/scripts/gen-plugin-facts.ts.
        'src/plugin-permissions.ts',
        // Per-locale string tables are data, not executable code; the parity
        // specs import every locale, which would report them as 100% covered
        // and inflate the package number.
        'src/i18n/*/**',
      ],
    },
  },
});
